### ISSUE TITLE
brew install error

### ISSUE THREAD

**Issue by dongwooklee96** [elixir-tools/homebrew-tap#21]
```
$brew install elixir-tools/tap/next-ls
```

==> Fetching elixir-tools/tap/next-ls
==> Downloading https://ziglang.org/download/0.11.0/zig-macos-aarch64-0.11.0.tar.xz
Already downloaded: /Users/dwlee/Library/Caches/Homebrew/downloads/20392e7bdbb6bef554e56d2b45a6b4dcf42a1a23f858d751afcc02109b78088e--zig-macos-aarch64-0.11.0.tar.xz
==> Downloading https://github.com/elixir-tools/next-ls/archive/refs/tags/v0.15.0.tar.gz
Already downloaded: /Users/dwlee/Library/Caches/Homebrew/downloads/f1a1fa41f89670964b4d3f27250ef182a734c073f7a7ba60e59d9d5ed911b2ea--next-ls-0.15.0.tar.gz
==> Installing next-ls from elixir-tools/tap
==> Downloading https://ziglang.org/download/0.11.0/zig-macos-aarch64-0.11.0.tar.xz
Already downloaded: /Users/dwlee/Library/Caches/Homebrew/downloads/20392e7bdbb6bef554e56d2b45a6b4dcf42a1a23f858d751afcc02109b78088e--zig-macos-aarch64-0.11.0.tar.xz
==> tar xvC /private/tmp/next-ls-20240130-54815-vucjf/next-ls-0.15.0/zig -f /Users/dwlee/Library/Caches/Homebrew/downloads/20392e7bdbb6bef554e56d2b45a6b4dcf42a1a23f858d751afcc02109b78088e
==> mix local.hex --force
==> mix local.rebar --force
==> mix deps.get
==> mix release
Last 15 lines from /Users/dwlee/Library/Logs/Homebrew/next-ls/05.mix:
	Debug: false
----> PHASE: :fetch
--> Working directory: /private/tmp/burrito_build_C8DA2DEC892F18E4
--> Resolving ERTS: {:precompiled, [version: "26.2.1"]}
--> Remote ERTS From Beam Machine: https://burrito-otp.b-cdn.net/OTP-26.2.1/darwin/aarch64/otp_26.2.1_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://burrito-otp.b-cdn.net/OTP-26.2.1/darwin/aarch64/otp_26.2.1_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://burrito-otp.b-cdn.net/OTP-26.2.1/darwin/aarch64/otp_26.2.1_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 0.8.0) lib/util/default_erts_resolver.ex:95: Burrito.Util.DefaultERTSResolver.do_download/2
    (burrito 0.8.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 0.8.0) lib/steps/fetch/resolve_erts.ex:34: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.16.0) lib/mix/tasks/release.ex:1076: Mix.Tasks.Release.run_steps/1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/elixir-tools/homebrew-tap/issues

**Comment by mhanberg** [comment]
https://github.com/elixir-tools/homebrew-tap/issues/8#issuecomment-1947405549
