### ISSUE TITLE
brew install error

### ISSUE THREAD

**Issue by vrypcow3807** [elixir-tools/homebrew-tap#8]
OS: macOS 14.0
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

brew install elixir-tools/tap/next-ls

==> Fetching elixir-tools/tap/next-ls
==> Downloading https://ziglang.org/download/0.10.0/zig-macos-aarch64-0.10.0.tar.xz
Already downloaded: /Users/quentin/Library/Caches/Homebrew/downloads/e44c054d2e2a51bca6fdeafede8de819f0b23aed9bb4da0d4919ccceb45dc333--zig-macos-aarch64-0.10.0.tar.xz
==> Downloading https://github.com/elixir-tools/next-ls/archive/refs/tags/v0.12.6.tar.gz
Already downloaded: /Users/quentin/Library/Caches/Homebrew/downloads/2a9b66aa2d86190c0dccfcf22bf23b11444d5fa52f222d9fb143d88e6a9ffaf8--next-ls-0.12.6.tar.gz
==> Installing next-ls from elixir-tools/tap
==> Downloading https://ziglang.org/download/0.10.0/zig-macos-aarch64-0.10.0.tar.xz
Already downloaded: /Users/quentin/Library/Caches/Homebrew/downloads/e44c054d2e2a51bca6fdeafede8de819f0b23aed9bb4da0d4919ccceb45dc333--zig-macos-aarch64-0.10.0.tar.xz
==> tar xvC /private/tmp/next-ls-20230928-36363-uvwp1x/next-ls-0.12.6/zig -f /Users/quentin/Library/Caches/Homebrew/downloads/e44c054d2e2a51
==> mix local.hex --force
==> mix local.rebar --force
==> mix deps.get
==> mix release
Last 15 lines from /Users/quentin/Library/Logs/Homebrew/next-ls/05.mix:
----> PHASE: :build
--> Generating wrapper metadata file...
error(link): undefined reference to symbol 'dyld_stub_binder'
error: UndefinedSymbolReference
--> Cleaning up...
--> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBuild.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.6) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.15.6) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
    (mix 1.15.6) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.6) lib/mix/cli.ex:92: Mix.CLI.run_task/2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/elixir-tools/homebrew-tap/issues

**Comment by mhanberg** [comment]
Hi, sorry I realized I wasn't "watching" this repo, so I didn't see this.

I'm trying to bump the formula now to the latest version, it should hopefully work once I convince homebrew CI to work.
